[build]
    command = "python3 scripts/tree.py"

[[redirects]]
    from = "/git/*"
    to = "https://ari-web.xyz/gh/files.ari-web.xyz/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/favicon.ico"
    to = "https://ari-web.xyz/favicon.ico"
    status = 200
    force = true

[[redirects]]
    from = "/robots.txt"
    to = "https://ari-web.xyz/robots.txt"
    status = 200
    force = true

[[redirects]]
    from = "/sitemap.xml"
    to = "https://ari-web.xyz/sitemap.xml"
    status = 200
    force = true

[[redirects]]
    from = "/netlify.toml"
    to = "https://ari-web.xyz/404.files.xyz"
    status = 404
    force = true

[[redirects]]
    from = "/*"
    to = "https://ari-web.xyz/404.files.xyz"
    status = 404
    force = false

# Processing
[build.processing]
    skip_processing = true
# --------------

[[headers]]
    for = "/files.json"

    [headers.values]
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Methods = "GET"

[[headers]]
    for = "/files_json_hash.txt"

    [headers.values]
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Methods = "GET"

[[headers]]
    for = "/*"

    [headers.values]
        Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Methods = "GET"
        X-Frame-Options = "deny"
        X-Content-Type-Options = "nosniff"
        Content-Security-Policy = "upgrade-insecure-requests"
        X-Permitted-Cross-Domain-Policies = "none"
        Referrer-Policy = "no-referrer"

