#!/usr/bin/env bash

set -e

prompt() {
    {
        echo " $1"
        printf ' >> '
        read -r line
        echo
    } >&2

    echo "$line"
}

kb() {
    what="$(prompt 'What to type [<file selection>]')"

    if [ ! "$what" ]; then
        what="$(prompt 'File path')"

        if [ ! "$what" ] || [ ! -f "$what" ]; then
            exit 1
        fi

        what="$(cat -- "$what")"
    fi

    wtim="$(prompt 'How many times [1]')"
    stim="$(prompt 'How much time [1s]')"
    sltim="$(prompt 'How much time every line [0.5s]')"
    dtim="$(prompt 'Delay betweek keystrokes [20ms]')"

    echo '============================'
    echo "Times: ${wtim:-default}"
    echo "Time: ${stim:-default}"
    echo "Line time: ${sltim:-default}"
    echo "Stroke time: ${dtim:-default}"
    echo '============================'

    sleep "${stim:-1s}"

    IFS=
    for _ in $(seq -- "${wtim:-1}"); do
        while read -r line; do
            sleep "${sltim:-0.5s}"

            xdotool type --delay "${dtim:-20ms}" "${line}"
            xdotool key Return
        done <<<"$what"
    done
}

main() {
    [ -f "$1" ] && kb <"$1" && return
    kb
}

main "$@"
